# Generated by Django 5.2.11 on 2026-02-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('job_role', models.CharField(max_length=50)),
                ('monthly_income', models.IntegerField()),
                ('overtime', models.BooleanField(default=False)),
                ('job_satisfaction', models.IntegerField(default=3)),
                ('years_at_company', models.IntegerField(default=1)),
                ('total_working_years', models.IntegerField(default=1)),
                ('job_level', models.IntegerField(default=1)),
            ],
        ),
    ]
